Merged with HEAD.
git-svn-id: https://svn.osgeo.org/gdal@15247 f0d54148-0727-0410-94bb-9a71ac55c965

diff --git a/sandbox/dron/gdal-warptest/configure b/sandbox/dron/gdal-warptest/configure
--- a/sandbox/dron/gdal-warptest/configure
+++ b/sandbox/dron/gdal-warptest/configure
@@ -862,6 +862,7 @@ PNG_SETTING
 TIFF_SETTING
 TIFF_OPTS
 GEOTIFF_SETTING
+GEOTIFF_INCLUDE
 JPEG_SETTING
 GIF_SETTING
 HAVE_OGDI
@@ -1590,8 +1591,9 @@ Optional Packages:
   --with-kakadu=ARG     Include Kakadu/JPEG2000 support
   --with-mrsid=ARG      Include MrSID support (ARG=path to MrSID DSDK or no)
   --with-jp2mrsid=ARG   Enable MrSID JPEG2000 support (ARG=yes/no)
-  --without-bsb         Disable BSB format (legal issues pending)
-  --without-grib        Disable GRIB format
+  --with-msg=ARG          Enable MSG driver (ARG=yes or no)
+  --without-bsb           Disable BSB driver (legal issues pending
+  --without-grib          Disable GRIB driver
   --without-ogr         Don't build OGR into shared library
   --with-mysql=ARG      Include MySQL (ARG=path to mysql_config) [default=no]
   --with-ingres=ARG     Include Ingres (ARG=$II_SYSTEM)
@@ -5829,13 +5831,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5832: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5834: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5835: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:5837: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5838: output\"" >&5)
+  (eval echo "\"\$as_me:5840: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -6932,7 +6934,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6935 "configure"' > conftest.$ac_ext
+  echo '#line 6937 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8623,11 +8625,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8626: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8628: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8630: \$? = $ac_status" >&5
+   echo "$as_me:8632: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8945,11 +8947,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8948: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8950: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8952: \$? = $ac_status" >&5
+   echo "$as_me:8954: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9050,11 +9052,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9053: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9055: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9057: \$? = $ac_status" >&5
+   echo "$as_me:9059: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9105,11 +9107,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9108: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9110: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9112: \$? = $ac_status" >&5
+   echo "$as_me:9114: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11865,7 +11867,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11868 "configure"
+#line 11870 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11965,7 +11967,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11968 "configure"
+#line 11970 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13993,11 +13995,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13996: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13998: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14000: \$? = $ac_status" >&5
+   echo "$as_me:14002: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14092,11 +14094,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14095: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14097: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14099: \$? = $ac_status" >&5
+   echo "$as_me:14101: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14144,11 +14146,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14147: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14149: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14151: \$? = $ac_status" >&5
+   echo "$as_me:14153: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21225,6 +21227,7 @@ TIFF_OPTS=${TIFF_OPTS}
 
 
 
+GEOTIFF_INCLUDE=
 
 # Check whether --with-geotiff was given.
 if test "${with_geotiff+set}" = set; then
@@ -21308,10 +21311,20 @@ fi
   fi
 
   if test "$GEOTIFF_SETTING" = "external" ; then
+
+        if test -r /usr/include/geotiff.h ; then
+      GEOTIFF_INCLUDE=
+    elif test -r /usr/include/geotiff/geotiff.h ; then
+      GEOTIFF_INCLUDE="-I/usr/include/geotiff"
+    fi
+
     LIBS="-lgeotiff $LIBS"
     echo "using pre-installed libgeotiff."
+
   else
+
     echo "using internal GeoTIFF code."
+
   fi
 
 elif test "$with_geotiff" = "internal" ; then
@@ -21477,6 +21490,8 @@ fi
 fi
 
 GEOTIFF_SETTING=$GEOTIFF_SETTING
+
+GEOTIFF_INCLUDE=$GEOTIFF_INCLUDE
 
 
 
@@ -22377,7 +22392,7 @@ fi
 
   else
 
-    if x"$with_hdf4" != x"" ; then
+    if test x"$with_hdf4" != x"" ; then
       { { echo "$as_me:$LINENO: error: HDF4 support requested with arg \"$with_hdf4\", but neither hdf4 nor mfhdf lib found" >&5
 echo "$as_me: error: HDF4 support requested with arg \"$with_hdf4\", but neither hdf4 nor mfhdf lib found" >&2;}
    { (exit 1); exit 1; }; }
@@ -22573,9 +22588,9 @@ else
 fi
 
 
-  if test "$HDF_LIB_NAME" = "missing" ; then
-    { { echo "$as_me:$LINENO: error: HDF4 support requested with arg $with_hdf4, but neither hdf4 nor mfhdf lib found" >&5
-echo "$as_me: error: HDF4 support requested with arg $with_hdf4, but neither hdf4 nor mfhdf lib found" >&2;}
+  if test "$HDF5_LIB_NAME" = "missing" ; then
+    { { echo "$as_me:$LINENO: error: HDF5 support requested with arg $with_hdf5, but no hdf5 lib found" >&5
+echo "$as_me: error: HDF5 support requested with arg $with_hdf5, but no hdf5 lib found" >&2;}
    { (exit 1); exit 1; }; }
   fi
 
@@ -23173,6 +23188,7 @@ KAKDIR=$KAKDIR
 
 
 MRSID_FLAGS=
+HAVE_MRSID=no
 
 
 # Check whether --with-mrsid was given.
@@ -23197,14 +23213,37 @@ echo "$as_me: MrSID support disabled." >&6;}
 
 else
 
-  { echo "$as_me:$LINENO: checking for lt_base.h in $with_mrsid/include/support" >&5
-echo $ECHO_N "checking for lt_base.h in $with_mrsid/include/support... $ECHO_C" >&6; }
-  if test -r "$with_mrsid/include/support/lt_base.h" ; then
+  MRSID_BASE="$with_mrsid/include"
+
+  { echo "$as_me:$LINENO: checking for lt_base.h in $MRSID_BASE/support" >&5
+echo $ECHO_N "checking for lt_base.h in $MRSID_BASE/support... $ECHO_C" >&6; }
+  if test -r "$MRSID_BASE/support/lt_base.h" ; then
+
     { echo "$as_me:$LINENO: result: found MrSID DSDK version 4.x or newer." >&5
 echo "${ECHO_T}found MrSID DSDK version 4.x or newer." >&6; }
-
     HAVE_MRSID=yes
-    MRSID_INCLUDE="-I$with_mrsid/include/base -I$with_mrsid/include/metadata -I$with_mrsid/include/mrsid_readers -I$with_mrsid/include/j2k_readers -I$with_mrsid/include/support"
+    MRSID_INCLUDE="-I$MRSID_BASE/base -I$MRSID_BASE/metadata -I$MRSID_BASE/mrsid_readers -I$MRSID_BASE/j2k_readers -I$MRSID_BASE/support"
+
+  else
+
+    { echo "$as_me:$LINENO: result: not found." >&5
+echo "${ECHO_T}not found." >&6; }
+
+    { echo "$as_me:$LINENO: checking for lt_base.h in $MRSID_BASE" >&5
+echo $ECHO_N "checking for lt_base.h in $MRSID_BASE... $ECHO_C" >&6; }
+    if test -r "$MRSID_BASE/lt_base.h" ; then
+
+      { echo "$as_me:$LINENO: result: found MrSID DSDK version 7.x or newer." >&5
+echo "${ECHO_T}found MrSID DSDK version 7.x or newer." >&6; };
+      HAVE_MRSID=yes
+      MRSID_INCLUDE="-I$MRSID_BASE"
+
+    fi
+
+  fi
+
+  if test $HAVE_MRSID = yes ; then
+
     MRSID_LIBS="-lltidsdk -lpthread"
 
     { echo "$as_me:$LINENO: checking for MG3ImageWriter.h in $with_mrsid/include/mrsid_writers" >&5
@@ -23232,19 +23271,25 @@ echo "$as_me: error: MrSID JPEG2000 support requested, but this is incompatible 
    { (exit 1); exit 1; }; }
     fi
 
-    if test "x$with_jp2mrsid" = "x" -a "$HAVE_KAKADU" = "no" \
-            -a -r $with_mrsid/3rd-party/lib/Release/libltikdu.a ; then
-      with_jp2mrsid=yes
-    fi
-    if test "x$with_jp2mrsid" = "xyes" \
-            -a ! -r $with_mrsid/3rd-party/lib/Release/libltikdu.a ; then
-      { { echo "$as_me:$LINENO: error: MrSID JPEG2000 support requested, but libltikdu.a not found." >&5
+    MRSID_KAKADU_LIB=no
+    if test "$HAVE_KAKADU" = "no" ; then
+      if test x"$with_jp2mrsid" = x"" -o x"$with_jp2mrsid" = x"yes" ; then
+        if test -r $with_mrsid/3rd-party/lib/Release/libltikdu.a ; then
+          with_jp2mrsid=yes
+          MRSID_KAKADU_LIB=-lltikdu
+        elif test -r $with_mrsid/3rd-party/lib/Release/liblt_kakadu.a ; then
+          with_jp2mrsid=yes
+          MRSID_KAKADU_LIB=-llt_kakadu
+        else
+          { { echo "$as_me:$LINENO: error: MrSID JPEG2000 support requested, but libltikdu.a not found." >&5
 echo "$as_me: error: MrSID JPEG2000 support requested, but libltikdu.a not found." >&2;}
    { (exit 1); exit 1; }; }
+        fi
+      fi
     fi
 
     if test "x$with_jp2mrsid" = "xyes" ; then
-      MRSID_LIBS="$MRSID_LIBS -lltikdu"
+      MRSID_LIBS="$MRSID_LIBS $MRSID_KAKADU_LIB"
       MRSID_FLAGS="-DMRSID_J2K $MRSID_FLAGS"
       { echo "$as_me:$LINENO: result: enabled" >&5
 echo "${ECHO_T}enabled" >&6; }
@@ -23283,17 +23328,63 @@ fi
 
 
 
+
+# Check whether --with-msg was given.
+if test "${with_msg+set}" = set; then
+  withval=$with_msg;
+fi
+
+
+HAVE_MSG=no
+HAVE_EUMETSATWT=no
+
+if test "x$with_msg" = "xyes" ; then
+    { echo "$as_me:$LINENO: checking for EUMETSAT Wavelet Transformation Software" >&5
+echo $ECHO_N "checking for EUMETSAT Wavelet Transformation Software... $ECHO_C" >&6; }
+
+    if test -d "frmts/msg/PublicDecompWT" -a \
+        -f "frmts/msg/PublicDecompWT/COMP/Inc/CImage.h"; then
+        HAVE_EUMETSATWT=yes
+    else
+        HAVE_EUMETSATWT=no
+    fi
+    { echo "$as_me:$LINENO: result: $HAVE_EUMETSATWT" >&5
+echo "${ECHO_T}$HAVE_EUMETSATWT" >&6; }
+fi
+
+{ echo "$as_me:$LINENO: checking for MSG" >&5
+echo $ECHO_N "checking for MSG... $ECHO_C" >&6; }
+
+if test "x$with_msg" = "xyes" -o "x$with_msg" = "x" \
+    -a "x$HAVE_EUMETSATWT" = "xyes"; then
+    OPT_GDAL_FORMATS="msg $OPT_GDAL_FORMATS"
+    HAVE_MSG=yes
+    { echo "$as_me:$LINENO: result: enabled" >&5
+echo "${ECHO_T}enabled" >&6; }
+else
+    HAVE_MSG=no
+    { echo "$as_me:$LINENO: result: not requested" >&5
+echo "${ECHO_T}not requested" >&6; }
+fi
+
+
+
+
 # Check whether --with-bsb was given.
 if test "${with_bsb+set}" = set; then
   withval=$with_bsb;
 fi
 
 
+{ echo "$as_me:$LINENO: checking for BSB" >&5
+echo $ECHO_N "checking for BSB... $ECHO_C" >&6; }
 if test "$with_bsb" = yes -o x"$with_bsb" = x ; then
-  echo checking for BSB ... enabled
-  OPT_GDAL_FORMATS="bsb $OPT_GDAL_FORMATS"
+    OPT_GDAL_FORMATS="bsb $OPT_GDAL_FORMATS"
+    { echo "$as_me:$LINENO: result: enabled" >&5
+echo "${ECHO_T}enabled" >&6; }
 else
-  echo checking for BSB ... disabled by user
+    { echo "$as_me:$LINENO: result: disabled by user" >&5
+echo "${ECHO_T}disabled by user" >&6; }
 fi
 
 
@@ -23304,14 +23395,19 @@ if test "${with_grib+set}" = set; then
 fi
 
 
+{ echo "$as_me:$LINENO: checking for GRIB" >&5
+echo $ECHO_N "checking for GRIB... $ECHO_C" >&6; }
 if test "$with_grib" = yes -o x"$with_grib" = x ; then
-  echo checking for GRIB ... enabled
-  OPT_GDAL_FORMATS="grib $OPT_GDAL_FORMATS"
-  HAVE_GRIB=yes
+    OPT_GDAL_FORMATS="grib $OPT_GDAL_FORMATS"
+    HAVE_GRIB=yes
+    { echo "$as_me:$LINENO: result: enabled" >&5
+echo "${ECHO_T}enabled" >&6; }
 else
-  echo checking for GRIB ... disabled by user
-  HAVE_GRIB=no
+    HAVE_GRIB=no
+    { echo "$as_me:$LINENO: result: disabled by user" >&5
+echo "${ECHO_T}disabled by user" >&6; }
 fi
+
 
 
 OPT_GDAL_FORMATS=$OPT_GDAL_FORMATS
@@ -28190,6 +28286,7 @@ for ac_last_try in false false false false false :; do
 TIFF_SETTING!$TIFF_SETTING$ac_delim
 TIFF_OPTS!$TIFF_OPTS$ac_delim
 GEOTIFF_SETTING!$GEOTIFF_SETTING$ac_delim
+GEOTIFF_INCLUDE!$GEOTIFF_INCLUDE$ac_delim
 JPEG_SETTING!$JPEG_SETTING$ac_delim
 GIF_SETTING!$GIF_SETTING$ac_delim
 HAVE_OGDI!$HAVE_OGDI$ac_delim
@@ -28283,7 +28380,6 @@ PYTHON_CFLAGS!$PYTHON_CFLAGS$ac_delim
 PYTHON_LIBS!$PYTHON_LIBS$ac_delim
 PYTHON_LINK!$PYTHON_LINK$ac_delim
 PY_LD_SHARED!$PY_LD_SHARED$ac_delim
-PY_SO_EXT!$PY_SO_EXT$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -28325,6 +28421,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+PY_SO_EXT!$PY_SO_EXT$ac_delim
 PYTHON_DEV!$PYTHON_DEV$ac_delim
 HAVE_NUMPY!$HAVE_NUMPY$ac_delim
 NUMPY_FLAG!$NUMPY_FLAG$ac_delim
@@ -28333,7 +28430,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 6; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 7; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -29568,6 +29665,9 @@ echo "  ECW support:               ${ECW_SETTING}"
 
 
 echo "  MrSID support:             ${HAVE_MRSID}"
+
+
+echo "  MSG support:               ${HAVE_MSG}"
 
 
 echo "  GRIB support:              ${HAVE_GRIB}"
